import type { HealthProfile } from "@/types/domain";

export const DEFAULT_HEALTH_PROFILE: HealthProfile = {
  gender: "",
  ageYears: null,
  surgeryType: "Ileostomy reversal",
  surgeryTypeOther: "",
  surgeryDate: "",
  height: null,
  startingWeight: null,
  currentWeight: null,
  targetWeight: null,
  comorbidities: [],
  otherConditions: "",
  medications: "",
  supplements: "",
  allergies: "",
  intolerances: "",
  dietaryHistory: "",
  smokingStatus: "",
  smokingCigarettesPerDay: null,
  smokingYears: null,
  alcoholUse: "",
  alcoholAmountPerSession: "",
  alcoholFrequency: "",
  alcoholYearsAtCurrentLevel: null,
  recreationalDrugUse: "",
  recreationalCategories: [],
  recreationalStimulantsFrequency: "",
  recreationalStimulantsYears: null,
  recreationalDepressantsFrequency: "",
  recreationalDepressantsYears: null,
  lifestyleNotes: "",
};
