/**
 * useTransitMapGeometry.ts
 *
 * Geometry Manifest for the Caca Traca Digestive Transit Map.
 * Sprint 2.7 — WQ-320
 *
 * AUTO-GENERATED by generate_transit_map_geometry.py
 * Generated: 2026-03-21 13:23
 * Registry stations: 147 (9 Zone 1A + 29 Zone 1B + 59 Zone 2 + 50 Zone 3)
 *
 * DO NOT EDIT STATION SPECS MANUALLY.
 * To update: edit shared/foodRegistryData.ts, then re-run:
 *   python3 generate_transit_map_geometry.py
 *
 * To change the map layout (paths, colours, zoom centres):
 *   edit generate_transit_map_geometry.py — GEOMETRY CONFIGURATION section.
 *
 * All coordinates are on a 2000×2000 SVG ViewBox grid, center (1000, 1000).
 */

import type { FoodGroup, FoodLine } from "@shared/foodRegistry";

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface StationPosition {
  /** Matches registry canonical exactly — e.g. "white rice" */
  canonical: string;
  x: number;
  y: number;
  zone: "1A" | "1B" | "2" | "3";
  lineOrder: number;
  /** Shown as label at overview / corridor zoom level */
  isRepresentative: boolean;
}

export interface LineGeometry {
  line: FoodLine;
  group: FoodGroup;
  /** SVG path d attribute — cubic Bezier, radiates from center outward */
  path: string;
  color: string;
  colorDimmed: string;
  stations: StationPosition[];
}

export interface ZoneRing {
  zone: "1A" | "1B" | "2" | "3";
  radius: number;
  label: string;
  color: string;
}

export interface Interchange {
  line: FoodLine;
  zone: "1A" | "1B" | "2" | "3";
  x: number;
  y: number;
}

export interface ZoomLevel {
  level: 1 | 2 | 3 | 4;
  name: "overview" | "corridor" | "line" | "station";
  scale: number;
  translateX: number;
  translateY: number;
}

export interface MapGeometry {
  viewBox: { width: 2000; height: 2000 };
  center: { x: 1000; y: 1000 };
  zoneRings: ZoneRing[];
  lines: LineGeometry[];
  interchanges: Interchange[];
  zoomLevels: {
    overview: ZoomLevel;
    corridor: (group: FoodGroup) => ZoomLevel;
    line: (line: FoodLine) => ZoomLevel;
    station: (canonical: string) => ZoomLevel;
  };
}

// ---------------------------------------------------------------------------
// Zone ring radii — monotonically increasing: 1A < 1B < 2 < 3
// ---------------------------------------------------------------------------

export const ZONE_RADII: Record<"1A" | "1B" | "2" | "3", number> = {
  "1A": 160,
  "1B": 360,
  "2": 660,
  "3": 920,
};

export const ZONE_RINGS: ZoneRing[] = [
  { zone: "1A", radius: 160, label: "Zone 1A", color: "rgba(120,180,140,0.18)" },
  { zone: "1B", radius: 360, label: "Zone 1B", color: "rgba(120,160,200,0.15)" },
  { zone: "2", radius: 660, label: "Zone 2", color: "rgba(160,140,100,0.13)" },
  { zone: "3", radius: 920, label: "Zone 3", color: "rgba(200,100,80,0.10)" },
];

// ---------------------------------------------------------------------------
// Status colours (from evidence engine)
// ---------------------------------------------------------------------------

export const STATUS_COLORS = {
  untested: "rgba(160,160,160,0.30)",
  building: "#3b82f6",
  safe: "#22c55e",
  watch: "#f59e0b",
  avoid: "#ef4444",
} as const;

// ---------------------------------------------------------------------------
// Corridor colour palette
// ---------------------------------------------------------------------------

export const LINE_COLORS: Record<FoodLine, { color: string; colorDimmed: string }> = {
  meat_fish: { color: "#e11d48", colorDimmed: "#e11d4866" },
  eggs_dairy: { color: "#c2410c", colorDimmed: "#c2410c66" },
  vegetable_protein: { color: "#9f1239", colorDimmed: "#9f123966" },
  grains: { color: "#0284c7", colorDimmed: "#0284c766" },
  vegetables: { color: "#0891b2", colorDimmed: "#0891b266" },
  fruit: { color: "#1d4ed8", colorDimmed: "#1d4ed866" },
  oils: { color: "#d97706", colorDimmed: "#d9770666" },
  dairy_fats: { color: "#b45309", colorDimmed: "#b4530966" },
  nuts_seeds: { color: "#92400e", colorDimmed: "#92400e66" },
  sauces_condiments: { color: "#16a34a", colorDimmed: "#16a34a66" },
  herbs_spices: { color: "#15803d", colorDimmed: "#15803d66" },
};

// ---------------------------------------------------------------------------
// SVG Path Definitions — 11 organic cubic Bezier curves on 2000×2000 grid
// ---------------------------------------------------------------------------
//
// Angular layout (degrees from positive-x axis, SVG convention):
//   Protein corridor:    ~145° – 215°   (west)
//   Carbs corridor:      ~240° – 310°   (north-west)
//   Fats corridor:       ~330° –  40°   (north-east / east)
//   Seasoning corridor:   ~50° – 115°   (south-east)
//
// To redesign the map: edit LINE_PATHS in generate_transit_map_geometry.py

export const LINE_PATHS: Record<FoodLine, string> = {
  // meat_fish (protein) — 15 stations
  meat_fish: "M 882.4 1054.6 C 660.0 1100.0, 340.0 1090.0, 55.0 1083.0",

  // eggs_dairy (protein) — 12 stations
  eggs_dairy: "M 870.3 1040.7 C 630.0 1120.0, 350.0 1280.0, 178.0 1468.0",

  // vegetable_protein (protein) — 3 stations
  vegetable_protein: "M 840.0 1013.8 C 600.0 940.0, 350.0 700.0, 178.0 530.0",

  // grains (carbs) — 30 stations
  grains: "M 958.4 882.2 C 920.0 640.0, 1060.0 310.0, 1168.0 68.0",

  // vegetables (carbs) — 31 stations
  vegetables: "M 1000.0 840.0 C 960.0 600.0, 700.0 340.0, 524.0 178.0",

  // fruit (carbs) — 21 stations
  fruit: "M 1040.7 870.3 C 1160.0 660.0, 1420.0 420.0, 1612.0 272.0",

  // oils (fats) — 3 stations
  oils: "M 1112.2 958.4 C 1340.0 860.0, 1620.0 670.0, 1820.0 524.0",

  // dairy_fats (fats) — 8 stations
  dairy_fats: "M 1128.0 979.0 C 1370.0 950.0, 1700.0 978.0, 1950.0 1000.0",

  // nuts_seeds (fats) — 6 stations
  nuts_seeds: "M 1128.0 1021.0 C 1360.0 1090.0, 1630.0 1310.0, 1820.0 1476.0",

  // sauces_condiments (seasoning) — 12 stations
  sauces_condiments: "M 1040.7 1129.7 C 1150.0 1340.0, 1415.0 1572.0, 1612.0 1728.0",

  // herbs_spices (seasoning) — 6 stations
  herbs_spices: "M 1000.0 1160.0 C 972.0 1376.0, 806.0 1678.0, 674.0 1894.0",
};

// ---------------------------------------------------------------------------
// Zone segment fractions along each path
// ---------------------------------------------------------------------------

export const ZONE_SEGMENTS: Record<"1A" | "1B" | "2" | "3", [number, number]> = {
  "1A": [0.0, 0.12],
  "1B": [0.12, 0.32],
  "2": [0.32, 0.68],
  "3": [0.68, 1.0],
};

export const STATION_RADIUS = 6;
export const HITBOX_RADIUS = 22;
export const MIN_SPACING = 16;

// ---------------------------------------------------------------------------
// Station Registry — auto-generated from shared/foodRegistryData.ts
// ---------------------------------------------------------------------------
//
// Format: [canonical, zone, lineOrder, isRepresentative]
// DO NOT EDIT MANUALLY. Re-run generate_transit_map_geometry.py instead.

type ZoneId = "1A" | "1B" | "2" | "3";
type StationSpec = [string, ZoneId, number, boolean];

export const STATION_SPECS: Record<FoodLine, StationSpec[]> = {
  // meat_fish: 15 stations
  meat_fish: [
    ["clear broth", "1A", 1, true],
    ["boiled fish", "1B", 2, true],
    ["boiled white meat", "1B", 3, false],
    ["grilled white meat", "2", 4, true],
    ["cooked fish", "2", 5, false],
    ["lean minced meat", "2", 6, false],
    ["red meat", "2", 7, false],
    ["oily fish", "2", 8, false],
    ["ham", "2", 9, false],
    ["fast food burger", "3", 10, false],
    ["processed meat", "3", 11, false],
    ["battered fish", "3", 12, false],
    ["chili con carne", "3", 13, false],
    ["stir fry", "3", 14, false],
    ["curry dish", "3", 15, false],
  ],

  // eggs_dairy: 12 stations
  eggs_dairy: [
    ["protein drink", "1A", 6, false],
    ["plain yogurt", "1B", 1, true],
    ["egg", "1B", 2, true],
    ["milk", "1B", 3, true],
    ["cottage cheese", "1B", 4, false],
    ["custard", "1B", 5, false],
    ["smooth mousse", "1B", 12, false],
    ["buttered scrambled eggs", "2", 7, false],
    ["flavoured yogurt", "2", 8, false],
    ["milk pudding", "2", 9, false],
    ["kefir", "2", 10, false],
    ["fried egg", "2", 11, false],
  ],

  // vegetable_protein: 3 stations
  vegetable_protein: [
    ["tofu", "2", 1, true],
    ["legumes", "3", 3, false],
    ["mild veggie burger", "3", 4, false],
  ],

  // grains: 30 stations
  grains: [
    ["gelatin dessert", "1A", 0, false],
    ["white rice", "1B", 2, true],
    ["toast", "1B", 3, true],
    ["soaked cracker", "1B", 4, false],
    ["white bread", "1B", 5, true],
    ["white pasta", "1B", 6, false],
    ["noodles", "1B", 7, false],
    ["rice cracker", "1B", 8, false],
    ["porridge", "1B", 9, false],
    ["rice pudding", "1B", 10, false],
    ["soft couscous", "1B", 11, false],
    ["soft polenta", "1B", 12, false],
    ["semolina", "1B", 19, false],
    ["crispy cracker", "2", 13, false],
    ["plain biscuit", "2", 14, false],
    ["low-fiber cereal", "2", 15, false],
    ["basic savoury snack", "2", 16, false],
    ["low-fiber sweet snack", "2", 17, false],
    ["simple chocolate snack", "2", 18, false],
    ["plain pancake", "2", 20, false],
    ["bagel", "2", 28, false],
    ["pizza", "3", 21, false],
    ["wholegrain bread", "3", 22, false],
    ["brown rice", "3", 23, false],
    ["sweet biscuit", "3", 24, false],
    ["high-sugar refined snack", "3", 25, false],
    ["dark chocolate", "3", 26, false],
    ["refined confectionery", "3", 27, false],
    ["alcohol", "3", 29, false],
    ["carbonated drink", "3", 30, false],
  ],

  // vegetables: 31 stations
  vegetables: [
    ["smooth soup", "1A", 0, false],
    ["water", "1A", 1, false],
    ["tea", "1A", 24, false],
    ["electrolyte drink", "1A", 25, false],
    ["mashed potato", "1B", 2, true],
    ["mashed root vegetable", "1B", 3, false],
    ["mashed sweet potato", "1B", 26, false],
    ["boiled carrot", "2", 4, true],
    ["baked potato", "2", 5, false],
    ["sweet potato", "2", 6, false],
    ["cooked pumpkin", "2", 7, false],
    ["courgette", "2", 8, true],
    ["peeled cucumber", "2", 9, false],
    ["parsnip", "2", 10, false],
    ["cooked spinach", "2", 11, false],
    ["cooked tomato", "2", 12, false],
    ["cooked bell pepper", "2", 13, false],
    ["swede", "2", 14, false],
    ["cauliflower", "2", 15, false],
    ["boiled potato", "2", 27, false],
    ["cooked beetroot", "2", 28, false],
    ["plant milk", "2", 29, false],
    ["roasted potato", "3", 16, false],
    ["broccoli", "3", 17, false],
    ["green beans", "3", 18, false],
    ["leek", "3", 19, false],
    ["onion", "3", 20, false],
    ["sweetcorn", "3", 21, false],
    ["raw salad", "3", 22, false],
    ["mushrooms", "3", 23, false],
    ["coffee", "3", 30, false],
  ],

  // fruit: 21 stations
  fruit: [
    ["diluted juice", "1A", 0, false],
    ["ice lolly", "1A", 15, false],
    ["ripe banana", "1B", 1, true],
    ["stewed apple", "1B", 2, true],
    ["canned pear", "1B", 3, false],
    ["canned peach", "1B", 4, false],
    ["melon", "2", 5, true],
    ["ripe mango", "2", 6, false],
    ["peeled apple", "2", 7, false],
    ["grapes", "2", 17, false],
    ["canned mandarin", "2", 18, false],
    ["mandarin", "3", 8, false],
    ["kiwi", "3", 9, false],
    ["citrus fruit", "3", 10, false],
    ["pineapple", "3", 11, false],
    ["strawberries", "3", 12, false],
    ["dried fruit", "3", 13, false],
    ["exotic fruit", "3", 14, false],
    ["apple", "3", 16, false],
    ["fig", "3", 19, false],
    ["pomegranate", "3", 20, false],
  ],

  // oils: 3 stations
  oils: [
    ["olive oil", "1B", 1, true],
    ["vegetable oil", "2", 2, false],
    ["deep fried food", "3", 3, false],
  ],

  // dairy_fats: 8 stations
  dairy_fats: [
    ["butter", "2", 1, true],
    ["cream cheese", "2", 2, true],
    ["hard cheese", "2", 3, false],
    ["mozzarella", "2", 4, false],
    ["cream", "2", 5, false],
    ["plain ice cream", "2", 6, false],
    ["soft rind cheese", "3", 7, false],
    ["double cream", "3", 8, false],
  ],

  // nuts_seeds: 6 stations
  nuts_seeds: [
    ["avocado", "2", 1, true],
    ["smooth nut butter", "2", 2, false],
    ["nuts", "3", 3, false],
    ["seeds", "3", 4, false],
    ["guacamole", "3", 5, false],
    ["coconut", "3", 6, false],
  ],

  // sauces_condiments: 12 stations
  sauces_condiments: [
    ["salt", "1B", 1, true],
    ["soy sauce", "2", 2, false],
    ["smooth tomato sauce", "2", 3, true],
    ["mild mustard", "2", 4, false],
    ["white sauce", "2", 5, false],
    ["gravy", "2", 6, false],
    ["honey", "2", 7, false],
    ["jam", "2", 8, false],
    ["citrus juice", "2", 12, false],
    ["miso soup", "3", 9, false],
    ["hot sauce", "3", 10, false],
    ["non-sugar sweetener", "3", 11, false],
  ],

  // herbs_spices: 6 stations
  herbs_spices: [
    ["mild herb", "2", 2, true],
    ["mild spice", "2", 3, false],
    ["black pepper", "3", 4, false],
    ["garlic", "3", 5, false],
    ["chili", "3", 6, false],
    ["hot spice blend", "3", 7, false],
  ],
};

// ---------------------------------------------------------------------------
// Corridor and line visual centres (for zoom level calculations)
// ---------------------------------------------------------------------------

const CORRIDOR_CENTERS: Record<FoodGroup, { x: number; y: number }> = {
  protein: { x: 580, y: 1020 },
  carbs: { x: 880, y: 580 },
  fats: { x: 1420, y: 900 },
  seasoning: { x: 1320, y: 1420 },
};

const LINE_CENTERS: Record<FoodLine, { x: number; y: number }> = {
  meat_fish: { x: 470, y: 1085 },
  eggs_dairy: { x: 510, y: 1260 },
  vegetable_protein: { x: 490, y: 740 },
  grains: { x: 890, y: 490 },
  vegetables: { x: 760, y: 490 },
  fruit: { x: 1120, y: 570 },
  oils: { x: 1460, y: 740 },
  dairy_fats: { x: 1540, y: 990 },
  nuts_seeds: { x: 1460, y: 1260 },
  sauces_condiments: { x: 1310, y: 1520 },
  herbs_spices: { x: 890, y: 1620 },
};

// ---------------------------------------------------------------------------
// Zoom level helper
// ---------------------------------------------------------------------------

function zoomTo(
  level: 1 | 2 | 3 | 4,
  name: ZoomLevel["name"],
  scale: number,
  cx: number,
  cy: number,
): ZoomLevel {
  const half = 1000;
  return {
    level,
    name,
    scale,
    translateX: half / scale - cx,
    translateY: half / scale - cy,
  };
}

// ---------------------------------------------------------------------------
// Pure-TypeScript Bezier math (SSR-safe, no DOM required)
// ---------------------------------------------------------------------------

function cubicBezierPoint(
  p0: [number, number],
  p1: [number, number],
  p2: [number, number],
  p3: [number, number],
  t: number,
): [number, number] {
  const mt = 1 - t;
  return [
    mt * mt * mt * p0[0] + 3 * mt * mt * t * p1[0] + 3 * mt * t * t * p2[0] + t * t * t * p3[0],
    mt * mt * mt * p0[1] + 3 * mt * mt * t * p1[1] + 3 * mt * t * t * p2[1] + t * t * t * p3[1],
  ];
}

function buildArcLengthTable(
  p0: [number, number],
  p1: [number, number],
  p2: [number, number],
  p3: [number, number],
  steps = 200,
): number[] {
  const table: number[] = [0];
  let prev = p0;
  for (let i = 1; i <= steps; i++) {
    const curr = cubicBezierPoint(p0, p1, p2, p3, i / steps);
    const dx = curr[0] - prev[0],
      dy = curr[1] - prev[1];
    table.push(table[i - 1] + Math.sqrt(dx * dx + dy * dy));
    prev = curr;
  }
  return table;
}

function getPointAtFraction(
  p0: [number, number],
  p1: [number, number],
  p2: [number, number],
  p3: [number, number],
  fraction: number,
  table: number[],
): [number, number] {
  const totalLen = table[table.length - 1];
  const target = fraction * totalLen;
  const steps = table.length - 1;
  let lo = 0,
    hi = steps;
  while (lo < hi - 1) {
    const mid = (lo + hi) >> 1;
    if (table[mid] < target) lo = mid;
    else hi = mid;
  }
  const segFrac =
    table[lo] === table[hi]
      ? lo / steps
      : (lo + (target - table[lo]) / (table[hi] - table[lo])) / steps;
  return cubicBezierPoint(p0, p1, p2, p3, segFrac);
}

function parseCubicPath(d: string): {
  p0: [number, number];
  p1: [number, number];
  p2: [number, number];
  p3: [number, number];
} {
  const clean = d.replace(/\s+/g, " ").trim();
  const mMatch = clean.match(/M\s*([\d.]+)\s+([\d.]+)/);
  const cMatch = clean.match(
    /C\s*([\d.]+)\s+([\d.]+)[,\s]+([\d.]+)\s+([\d.]+)[,\s]+([\d.]+)\s+([\d.]+)/,
  );
  if (!mMatch || !cMatch) throw new Error(`Cannot parse path: ${d}`);
  return {
    p0: [parseFloat(mMatch[1]), parseFloat(mMatch[2])],
    p1: [parseFloat(cMatch[1]), parseFloat(cMatch[2])],
    p2: [parseFloat(cMatch[3]), parseFloat(cMatch[4])],
    p3: [parseFloat(cMatch[5]), parseFloat(cMatch[6])],
  };
}

// ---------------------------------------------------------------------------
// Station interpolation (shared logic)
// ---------------------------------------------------------------------------

function interpolateStationsStatic(pathD: string, specs: StationSpec[]): StationPosition[] {
  const { p0, p1, p2, p3 } = parseCubicPath(pathD);
  const table = buildArcLengthTable(p0, p1, p2, p3);

  const byZone: Record<ZoneId, StationSpec[]> = { "1A": [], "1B": [], "2": [], "3": [] };
  for (const spec of specs) byZone[spec[1]].push(spec);
  for (const zone of ["1A", "1B", "2", "3"] as ZoneId[]) {
    byZone[zone].sort((a, b) => a[2] - b[2]);
  }

  const positions: StationPosition[] = [];
  for (const zone of ["1A", "1B", "2", "3"] as ZoneId[]) {
    const zoneSpecs = byZone[zone];
    if (zoneSpecs.length === 0) continue;
    const [segStart, segEnd] = ZONE_SEGMENTS[zone];
    const count = zoneSpecs.length;
    for (let i = 0; i < count; i++) {
      const spec = zoneSpecs[i];
      const t = segStart + (segEnd - segStart) * ((i + 1) / (count + 1));
      const [x, y] = getPointAtFraction(p0, p1, p2, p3, t, table);
      positions.push({
        canonical: spec[0],
        x: Math.round(x * 10) / 10,
        y: Math.round(y * 10) / 10,
        zone,
        lineOrder: spec[2],
        isRepresentative: spec[3],
      });
    }
  }
  return positions;
}

// ---------------------------------------------------------------------------
// Interchange positions (zone boundary crossings)
// ---------------------------------------------------------------------------

function computeInterchangesStatic(line: FoodLine, pathD: string): Interchange[] {
  const { p0, p1, p2, p3 } = parseCubicPath(pathD);
  const table = buildArcLengthTable(p0, p1, p2, p3);
  const boundaries: Array<[ZoneId, number]> = [
    ["1A", ZONE_SEGMENTS["1A"][1]],
    ["1B", ZONE_SEGMENTS["1B"][1]],
    ["2", ZONE_SEGMENTS["2"][1]],
  ];
  return boundaries.map(([zone, t]) => {
    const [x, y] = getPointAtFraction(p0, p1, p2, p3, t, table);
    return { line, zone, x: Math.round(x * 10) / 10, y: Math.round(y * 10) / 10 };
  });
}

// ---------------------------------------------------------------------------
// Line group helper
// ---------------------------------------------------------------------------

function lineGroup(line: FoodLine): FoodGroup {
  if (line === "meat_fish" || line === "eggs_dairy" || line === "vegetable_protein")
    return "protein";
  if (line === "grains" || line === "vegetables" || line === "fruit") return "carbs";
  if (line === "oils" || line === "dairy_fats" || line === "nuts_seeds") return "fats";
  return "seasoning";
}

// ---------------------------------------------------------------------------
// getStaticTransitMapGeometry — SSR-safe, no DOM required
// ---------------------------------------------------------------------------

let _staticCache: MapGeometry | null = null;

/**
 * Returns the complete MapGeometry using pure-TypeScript Bezier math.
 * Safe to call on the server (Next.js, Remix) or in a Worker.
 * Result is memoised after first call.
 */
export function getStaticTransitMapGeometry(): MapGeometry {
  if (_staticCache) return _staticCache;

  const allLines = Object.keys(STATION_SPECS) as FoodLine[];
  const lines: LineGeometry[] = allLines.map((line) => {
    const pathD = LINE_PATHS[line];
    const specs = STATION_SPECS[line];
    const { color, colorDimmed } = LINE_COLORS[line];
    const group = lineGroup(line);
    const stations = interpolateStationsStatic(pathD, specs);
    return { line, group, path: pathD, color, colorDimmed, stations };
  });

  const interchanges: Interchange[] = lines.flatMap((lg) =>
    computeInterchangesStatic(lg.line, lg.path),
  );

  const stationLookup = new Map(lines.flatMap((lg) => lg.stations.map((s) => [s.canonical, s])));

  const zoomLevels: MapGeometry["zoomLevels"] = {
    overview: zoomTo(1, "overview", 1.0, 1000, 1000),
    corridor: (group: FoodGroup) => {
      const c = CORRIDOR_CENTERS[group];
      return zoomTo(2, "corridor", 1.6, c.x, c.y);
    },
    line: (line: FoodLine) => {
      const c = LINE_CENTERS[line];
      return zoomTo(3, "line", 2.8, c.x, c.y);
    },
    station: (canonical: string) => {
      const s = stationLookup.get(canonical);
      return zoomTo(4, "station", 5.0, s?.x ?? 1000, s?.y ?? 1000);
    },
  };

  _staticCache = {
    viewBox: { width: 2000, height: 2000 },
    center: { x: 1000, y: 1000 },
    zoneRings: ZONE_RINGS,
    lines,
    interchanges,
    zoomLevels,
  };
  return _staticCache;
}

// ---------------------------------------------------------------------------
// useTransitMapGeometry — browser hook (uses SVGPathElement for precision)
// ---------------------------------------------------------------------------

function interpolateStationsBrowser(pathD: string, specs: StationSpec[]): StationPosition[] {
  if (typeof document === "undefined") {
    return interpolateStationsStatic(pathD, specs);
  }

  const svgNS = "http://www.w3.org/2000/svg";
  const pathEl = document.createElementNS(svgNS, "path") as SVGPathElement;
  pathEl.setAttribute("d", pathD);
  const svgEl = document.createElementNS(svgNS, "svg") as SVGSVGElement;
  svgEl.setAttribute("viewBox", "0 0 2000 2000");
  svgEl.style.cssText = "position:absolute;visibility:hidden;pointer-events:none;width:0;height:0;";
  svgEl.appendChild(pathEl);
  document.body.appendChild(svgEl);

  try {
    const totalLength = pathEl.getTotalLength();
    const byZone: Record<ZoneId, StationSpec[]> = { "1A": [], "1B": [], "2": [], "3": [] };
    for (const spec of specs) byZone[spec[1]].push(spec);
    for (const zone of ["1A", "1B", "2", "3"] as ZoneId[]) {
      byZone[zone].sort((a, b) => a[2] - b[2]);
    }

    const positions: StationPosition[] = [];
    for (const zone of ["1A", "1B", "2", "3"] as ZoneId[]) {
      const zoneSpecs = byZone[zone];
      if (zoneSpecs.length === 0) continue;
      const [segStart, segEnd] = ZONE_SEGMENTS[zone];
      const count = zoneSpecs.length;
      for (let i = 0; i < count; i++) {
        const spec = zoneSpecs[i];
        const t = segStart + (segEnd - segStart) * ((i + 1) / (count + 1));
        const pt = pathEl.getPointAtLength(t * totalLength);
        positions.push({
          canonical: spec[0],
          x: Math.round(pt.x * 10) / 10,
          y: Math.round(pt.y * 10) / 10,
          zone,
          lineOrder: spec[2],
          isRepresentative: spec[3],
        });
      }
    }

    return positions;
  } finally {
    document.body.removeChild(svgEl);
  }
}

let _browserCache: MapGeometry | null = null;

/**
 * useTransitMapGeometry
 *
 * Returns the complete MapGeometry for the Caca Traca transit map.
 * Computed once on first call and cached — stable reference for React memoisation.
 * Must be called in a browser context. For SSR use getStaticTransitMapGeometry().
 */
export function useTransitMapGeometry(): MapGeometry {
  if (_browserCache) return _browserCache;

  const allLines = Object.keys(STATION_SPECS) as FoodLine[];
  const lines: LineGeometry[] = allLines.map((line) => {
    const pathD = LINE_PATHS[line];
    const specs = STATION_SPECS[line];
    const { color, colorDimmed } = LINE_COLORS[line];
    const group = lineGroup(line);
    const stations = interpolateStationsBrowser(pathD, specs);
    return { line, group, path: pathD, color, colorDimmed, stations };
  });

  const interchanges: Interchange[] = lines.flatMap((lg) =>
    computeInterchangesStatic(lg.line, lg.path),
  );

  const stationLookup = new Map(lines.flatMap((lg) => lg.stations.map((s) => [s.canonical, s])));

  const zoomLevels: MapGeometry["zoomLevels"] = {
    overview: zoomTo(1, "overview", 1.0, 1000, 1000),
    corridor: (group: FoodGroup) => {
      const c = CORRIDOR_CENTERS[group];
      return zoomTo(2, "corridor", 1.6, c.x, c.y);
    },
    line: (line: FoodLine) => {
      const c = LINE_CENTERS[line];
      return zoomTo(3, "line", 2.8, c.x, c.y);
    },
    station: (canonical: string) => {
      const s = stationLookup.get(canonical);
      return zoomTo(4, "station", 5.0, s?.x ?? 1000, s?.y ?? 1000);
    },
  };

  _browserCache = {
    viewBox: { width: 2000, height: 2000 },
    center: { x: 1000, y: 1000 },
    zoneRings: ZONE_RINGS,
    lines,
    interchanges,
    zoomLevels,
  };
  return _browserCache;
}

// ---------------------------------------------------------------------------
// SVG Rendering Reference (usage snippets for TransitMapCanvas.tsx)
// ---------------------------------------------------------------------------
//
// Track path — zoom-invariant stroke weight:
//   <path d={lg.path} stroke={lg.color} strokeWidth={3} fill="none"
//         vectorEffect="non-scaling-stroke" />
//
// Visible station circle:
//   <circle cx={s.x} cy={s.y} r={6} fill={statusColor} />
//
// Invisible hitbox — 44px touch target (WCAG 2.5.8):
//   <circle cx={s.x} cy={s.y} r={22} fill="transparent"
//           style={{ cursor: "pointer" }} aria-label={s.canonical}
//           onClick={() => onStationFocus(s.canonical)} />
//
// Zone ring arc:
//   <circle cx={1000} cy={1000} r={ring.radius} fill="none"
//           stroke={ring.color} strokeWidth={1}
//           vectorEffect="non-scaling-stroke" />
//
// Zoom level 4 — inspector NEVER overlays the map (side-by-side only):
//   <div style={{ display: "flex" }}>
//     <svg style={{ flex: "0 0 50%" }}>{/* zoomed station cluster */}</svg>
//     <div style={{ flex: "0 0 50%" }}>{/* StationCallout — sibling, not overlay */}</div>
//   </div>

export { CORRIDOR_CENTERS, LINE_CENTERS };
